### PR TITLE
gitlab: support repo creation in group (namespace)

### LINKED ISSUE #51: git repo <target> create for group/organisations namespaces
When creating a git repo for a group at Gitlab, I would want to call git-repo with the arguments `lab create <groupname>/<reponame>`, but this results in the repo being created for my current user, and not for the group.

### PR DESCRIPTION
**Pull request by peterazmanov**
Enable creation of repository in group. Tested on self-hosted gitlab-ce.
Not sure if my changes are sufficient for full support of the feature.
Fixes #51 for gitlab.

### CODE REVIEW

**Comment by guyzmo** [comment]
wha, that's ♥
It'd be great if you wrote a test for it as well, you could write something about that following up on:

https://github.com/guyzmo/git-repo/blob/master/tests/integration/test_gitlab.py#L42-L51

Though, to make the tests easier, maybe should we consider an API to create a group as well? (or simply use a direct call to the `Gitlab` instance to create the group first).

I want stuff to be well tested for the main API of the application… But I have to admit the test framework has only really been working so far for me and the main travis, and I'm not sure why it keeps on failing on incoming PR, and I don't know if it's working for other people :-s

**Comment by guyzmo** [comment]
(I'm doing a bugfix that I'll push in a branch for the issue that crashes the CI in PRs, then you'll have to rebase your PR on it)

**Comment by guyzmo** [comment]
Could you rebase your code onto #53 (or the `bugfix/conftest_fix` branch)?

I'd like to see PR builds on travis work fine ☺

**Comment by peterazmanov** [comment]
Done.

**Comment by guyzmo** [comment]
Thanks!

ok, so there are a few errors that I don't get and are not related to your build, but there are a couple that are definitely related. Basically, you're adding one new request per `create` action so [those two tests](https://github.com/guyzmo/git-repo/blob/devel/tests/integration/test_gitlab.py#L42,L51) are failing because the betamax record is lacking the API call to `groups.search()`.

**Comment by peterazmanov** [comment]
I'm not familiar with betamax, in fact I've never heard of it before. As far as I understand, 'cassettes' for these tests should be recorded anew after my changes. I'm not sure I'm the right person for the job. :smiley:

**Comment by guyzmo** [comment]
it's alright, I've written the tests for this code ☺

**Comment by guyzmo** [comment]
so I've pushed a few more commits in the branch [requests/52](https://github.com/guyzmo/git-repo/tree/request/52)… I tried pushing new commits to this PR but it looks like it's not allowed by github.

About the cassettes, it's not that complex. 

In [`conftests.py` I've configured the record mode to happen once](https://github.com/guyzmo/git-repo/blob/request/52/tests/conftest.py#L8). So it means that if you delete the cassette matching the test like [`test_gitlab_01_create__already_exists`](https://github.com/guyzmo/git-repo/blob/request/52/tests/integration/cassettes/test_gitlab_test_01_create__already_exists.json) it will start a new record of the HTTP exchanges happening with the code.

That means that you need to make sure that the test will behave as expected, i.e. for that last one, you need to have an existing repository with name `git-repo` in your own namespace.

Also, because the "default" namespace isn't guessed at testing time (I used to use your current's user username per default, but I figured it's actually wrong), it's using the environment variable `GITREPO_NAMESPACE` 
so I've pushed a few more commits in the branch [requests/52](https://github.com/guyzmo/git-repo/tree/request/52)… I tried pushing new commits to this PR but it looks like it's not allowed by github.

About the cassettes, it's quite simple actually. In [`conftests.py` I've configured the record mode to happen once](https://github.com/guyzmo/git-repo/blob/request/52/tests/conftest.py#L8). So it means that if you delete the cassette matching the test like [`test_gitlab_01_create__already_exists`](https://github.com/guyzmo/git-repo/blob/request/52/tests/integration/cassettes/test_gitlab_test_01_create__already_exists.json) it will start a new record of the HTTP exchanges happening with the code.

That means that you need to make sure that the test will behave as expected, i.e. for that last one, you need to have an existing repository with name `git-repo` in your own namespace.

Also, because the "default" namespace isn't guessed at testing time (I used to use your current's user username per default, but I figured it's actually wrong), it's using the environment variable `GITREPO_NAMESPACE` as your default namespace. So if you start the tests like:

``` shell
% rm /tests/integration/cassettes/test_gitlab_test_01_create__already_exists.json
% GITREPO_NAMESPACE=foobar bin/py.test
```

It will expect that your gitlab login username is `foobar`, and that there is a `foobar/git-repo` project existing in your project.

Then, writing a new test is easy, I've built a bunch of [helper methods](https://github.com/guyzmo/git-repo/blob/request/52/tests/helpers.py#L448-L784) that mirrors the API of the services, which takes care of all the cassette handling and the git repository mocking up. So to write a new test you need to use those methods and create [a new usage scenario](https://github.com/guyzmo/git-repo/blob/request/52/tests/integration/test_gitlab.py#L50-L52):

``` python
    def test_01_create_group__new(self):
        self.action_create(namespace='git-repo-test', repository='foobar')
```

**Comment by guyzmo** [comment]
I should really write a documentation about that, because I did my best to make it simple, but I know it's definitely not obvious 😖

**Comment by guyzmo** [comment]
ok, I've added the same feature for github (and its organizations) with matching tests. it's all merged in devel.

**Pull request closed without merging**
