### PR TITLE
Automatic Browser detection using Python built-ins

### PR DESCRIPTION
**Pull request by fa7ad**
PR as asked #159 :grin:

### CODE REVIEW

**Comment by guyzmo** [comment]
Thank you for the PR 🙌♥

**Comment by fa7ad** [comment]
Should be fine now

**Comment by guyhughes** [comment]
The github issue that brought this about has been updated: https://github.com/github/hub/issues/1473

xdg-open isn't deprecated:
> The fact that xdg-open calls gvfs-open (which then shows the message) before gio open is a bug caused by that deprecation and is fixed in xdg-utils 1.1.2.

That said, using the `webbrowser` stdlib module is probably an improvement anyway.

**Comment by fa7ad** [comment]
# ¯\\_(ツ)_\/¯

**Comment by guyzmo** [comment]
I consider this solution 👌 and thus I marked the patch as `ready` and it will make it to the 1.11 milestone. 

There's a bunch of updates I need to take care of as well and it'd be great if I could find the time to add features (issues, gpg, ssh are my goal).

**Comment by timofonic** [comment]
@guyzmo  Any news?

**Pull request closed without merging**
