### PR TITLE
Fix GitLab merge request fetch

### PR DESCRIPTION
**Pull request by jayvdb**
Reverts one chunk of e58373e2

### CODE REVIEW

**Comment by jayvdb** [comment]
c.f. https://docs.gitlab.com/ce/user/project/merge_requests/index.html for the fact that it should be `merge-requests`

**Comment by guyzmo** [comment]
errrrr… you're most likely right, but I did not invent those cassette records, so it has worked at some point. Let me double check the whys and hows,and test your fix.

But as the RTFM say so, I'm pretty sure it's alright and merge material 😉

**Comment by jayvdb** [comment]
I've asked if the branch name has changed at https://gitter.im/gitlabhq/gitlabhq?at=58c6bca109e7ba8510bcd274

**Comment by guyzmo** [comment]
@jayvdb you're welcome on [irc.freenode.org #git-repo](irc://irc.freenode.org/git-repo) for a chat!

**Comment by jayvdb** [comment]
Can we please get some traction on this.

Please look at https://gitlab.com/gitlab-org/gitlab-ce/commit/86bccb71a1d4 , which is August 2015, ensuring that all MRs (even MRs from branches instead of forks) have a usable ref.  The documentation there uses `merge-requests`.  So for as long as it has been possible to *always* use a ref, the documentation has always said the ref will be `merge-requests/*/head`. (see moves like https://gitlab.com/gitlab-org/gitlab-ce/commit/7973a22f and https://gitlab.com/gitlab-org/gitlab-ce/commit/4f5bb980 to follow that original .md to its current location).

`tests/integration/cassettes/test_gitlab_test_19_request_fetch.json` and `tests/integration/cassettes/test_gitlab_test_19_request_fetch__bad_request.json` both have only one commit (e58373e21, 11 Oct 2016), and neither mentions `merge-requests` or `merge_requests`.  ergo, the cassettes themselves have no opinion on whether it should be `merge-requests` or `merge_requests`.

That same commit had `test_19_request_fetch` using [`remote_branch='merge_requests'`](https://github.com/guyzmo/git-repo/commit/e58373e2144151b5427686bd153c44141c7d33f3#diff-48e5f0edb572625ff969258be86c10fcR240) and the gitlab adapter [changed](https://github.com/guyzmo/git-repo/commit/e58373e2144151b5427686bd153c44141c7d33f3#diff-6cda266ab3e820bbb573c2ac29a9844eR318):

```diff
-                       'merge-requests/{}/head'.format(request),
+                       'merge_requests/{}/head'.format(request),
```

But somehow you created those cassettes.  My guess is that you obtained the cassette before the change, and then you changed the code above, thus creating the bug, and committed the cassettes and code changes together, resulting in a buggy test method.  Anyway, it really doesnt matter if `merge_requests` ever worked somehow ... if it did, it was luck alone, as it isnt in accordance with the documentation.

**Comment by guyzmo** [comment]
Sorry for the loooong delay merging this small commit! But better late than never! 😉

I'm preparing a release for this week end, so stay tuned

**Pull request closed without merging**
